### PR TITLE
Pan shift

### LINKED ISSUE #117: Pan margin
Will be great to have a pan margin like in this video 
[video](https://drive.google.com/file/d/1tE_doBA5AohJDcV6hHIeZ57lFEh-1PQZ/view?usp=sharing) 

#116

### PR DESCRIPTION
**Pull request by Link184**
Added possibility to set pan margins to achieve a result like in this [video](https://drive.google.com/file/d/1tE_doBA5AohJDcV6hHIeZ57lFEh-1PQZ/view?usp=sharing)
fixes #117

### CODE REVIEW

**Comment by markusressel** [comment]
Why did you call it `shift` instead of `margin`/`padding`/`offset`?

**Comment by Link184** [comment]
> Why did you call it `shift` instead of `margin`/`padding`/`offset`?

Renamed shift to padding, also there is a problem with initial view alignment [screenshot](https://drive.google.com/file/d/19PmYA8Fgj3T9uZk5mrRzotQkWXYzqL7q/view?usp=sharing). Do you have any good ideas how to solve it?

**Comment by markusressel** [comment]
@Link184 No, sorry, I'm also currently not able to look into this.

**Comment by markusressel** [comment]
@Link184 I just pushed a fix for #158 which might help with your initial alignment problem. Are you able to have a look at this again?

**Review by AdminCarlos — APPROVED** [review]

**Pull request closed without merging**
