### PR TITLE
add missing invalidate call

### LINKED ISSUE #34: Scrollbars not rendered when fadeScrollbars="false"
Because of a missing "invalidate()" call (removed in the review of the recently PR) scrollbars are not rendered when the fadeScrollbars attribute is set to false.

This only applies to the ZoomLayout, the ZoomImageView is not affected, apparently because it uses ```setImageMatrix()``` which internally calls ```invalidate()``` on every draw.

I would just follow the documentation and call ```invalidate``` if ```awakenScrollbars()``` returns false.

I will create a PR for this issue shortly.

### PR DESCRIPTION
**Pull request by markusressel**
this fixes #34

### CODE REVIEW

**Comment by natario1** [comment]
What happens if you call just awakenScrollBars() but before all the rest, right after matrix.set()?
I'd like to avoid this extra invalidate call for who is not using scrollbars at all.

**Comment by markusressel** [comment]
Tried it didn't work. We can test though if vertical and/or horizontal scrollbar is enabled if you want.

**Comment by markusressel** [comment]
The problem is awakenScrollbars does nothing if fadeScrollbars is set to false. I don't know why the child views are rendered and the scrollbars are not, but the additional invalidate fixes it. If you know a better solution let me know.

**Comment by natario1** [comment]
Yeah this is confusing, but let's do it this way then 👍thanks for spotting this!

**Pull request merged**
